# Generated by Django 3.1.6 on 2026-01-23 21:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20260123_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (
                '-created_at',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(
                    db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='language.post')),
            ],
            options={
                'verbose_name': 'post Translation',
                'db_table': 'language_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
